
/*------------------------------------------------------------------------
    File        : totpHashMode
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : James
    Created     : Sat Sep 17 20:49:06 NZST 2022
    Notes       : 
  ----------------------------------------------------------------------*/

enum src.totpHashMode flags :  

    define enum hmac-sha-1
                hmac-sha-256
                hmac-sha-512.

end enum.